services:
  backend:
    build: ./backend
    container_name: foodhub-backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - PORT=5000
      - CLIENT_ORIGIN=http://localhost
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - foodhub-net

  frontend:
    build: ./frontend
    container_name: foodhub-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - foodhub-net

  mongodb:
    image: mongo:7
    container_name: foodhub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - foodhub-net

volumes:
  mongo-data:

networks:
  foodhub-net:
